### ISSUE TITLE
Crash on 0.2.2 when starting daemon

### ISSUE THREAD

**Issue by ThatOneCalculator** [crptmem/lianlinux#18] opened 2024-04-19 17:24 UTC
```
$ sudo lianlinux daemon
Found a LianLi-UNI FAN-SL-v1.8  controller
thread 'main' panicked at /home/kainoa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lianlinux-0.2.2/src/daemon/mod.rs:55:10:
called `Result::unwrap()` on an `Err` value: missing field `r2`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by crptmem** [comment] 2024-04-20 12:02
Can you show me how your config looks like?

**Comment by ThatOneCalculator** [comment] 2024-04-20 20:10
`/etc/lianlinux/config.toml`:
```toml
current = "static"
r = 25
b = 25
g = 64
```

**Comment by crptmem** [comment] 2024-04-21 07:38
Version 0.2.2 added new config entries: `r2`, `g2`, `b2` for modes like runway. Here is an example of updated config:
current = "runway"
r2 = 112 # background
b2 = 20
g2 = 242
r = 0 # foreground
b = 245
g = 155

**Comment by ThatOneCalculator** [comment] 2024-04-21 08:08
Ah, gotcha. Maybe it should crash at least with a specific error message rather than an ambiguous traceback

**Comment by crptmem** [comment] 2024-04-21 08:40
> Maybe it should crash at least with a specific error message rather than an ambiguous traceback
Added in [df08992](https://github.com/crptmem/lianlinux/commit/df089929d84e45e172e5d6ef606646f467f98066)

**Comment by crptmem** [comment] 2024-04-21 16:26
Closing because as I see the issue is resolved.

**Closed by crptmem** 2024-04-21 16:26 UTC
